### ISSUE TITLE
No module named base58

### ISSUE THREAD

**Issue by MiniGlome** [lockedbyte/cryptovenom#15]
I have this issue when running the code with python2 

```
Traceback (most recent call last):
  File "modules/classical/adfgvx/menu.py", line 25, in <module>
    from main import *
  File "/home/me/cryptovenom/modules/classical/adfgvx/main.py", line 26, in <module>
    import base58
ImportError: No module named base58
```

**Comment by lockedbyte** [comment]
Hi,

Have you tried `pip install base58`?
